<?php 
/**
 * IDEALIAGroup srl
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.idealiagroup.com/magento-ext-license.html
 *
 * @category   IG
 * @package    IG_EuroSuite
 * @copyright  Copyright (c) 2010-2011 IDEALIAGroup srl (http://www.idealiagroup.com)
 * @license    http://www.idealiagroup.com/magento-ext-license.html
 */
?>

<?php $eurosuite = $this->getEuroSuite() ?>
<div class="newsletter-subscribe">
    <div class="page-title">
        <h1><?php echo $this->__('Newsletter') ?></h1>
    </div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<form action="<?php echo $this->getFormAction() ?>" method="post" id="newsletter-validate-detail2">
		<div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Sign up for our newsletter:') ?></h2>
            <ul class="form-list">
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>

	        	<?php if ($eurosuite->isPrivacyRequired('newsletter')): ?>
	            <li class="control">
					<div class="input-box">
						<input type="checkbox" name="privacy" id="privacy" class="checkbox required-entry" />
					</div>
					<label for="privacy" class="required"><em>*</em><?php echo Mage::helper('ig_eurosuite/tos')->getPrivacyText() ?></label>
				</li>
				<?php endif; ?>
				<?php if ($eurosuite->isTosRequired('newsletter')): ?>
				<li class="control">
					<div class="input-box">
						<input type="checkbox" name="tos" id="tos" class="checkbox required-entry" />
					</div>
					<label for="tos" class="required"><em>*</em><?php echo Mage::helper('ig_eurosuite/tos')->getTosText() ?></label>
	            </li>
				<?php endif; ?>
			</ul>
		</div>
		
		<div class="actions">
            <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
        </div>
	</form>
	<script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail2');
    //]]>
    </script>
	
</div>