<?php

/**
 * Crea gli head necessari per facebook
 * 
 */
if (Mage::getStoreConfig('autelsocial/settings/enabled', Mage::app()->getStore()->getId())): ?>

    <meta property="og:site_name" content="<?php echo Mage::getStoreConfig('general/store_information/name', Mage::app()->getStore()->getId()); ?>" />
    <meta property="og:type" content="website" />
    <?php if (!is_null(Mage::registry('current_product'))): 
        $product = Mage::getModel('catalog/product')->Load(Mage::registry('current_product')->getId());
        $imgUrl = '';
        $mediaGallery = $product->getData();

        if (isset ($mediaGallery['fb_like_image']) && $mediaGallery['fb_like_image'] != 'no_selection'):
            $imgUrl = Mage::helper('catalog/image')->init($product, 'fb_like_image', $product->getColorImage())->resize(250).'';
        endif;    
        if ($imgUrl == "" && isset($mediaGallery['image'])):
            $imgUrl = Mage::helper('catalog/image')->init($product, 'image', $product->getColorImage())->resize(250).'';
        endif;
        if ($imgUrl != ""):    
        endif;
    ?>
        <meta property="og:title" content="<?php echo  $product->getName(); ?>"/>  
        <meta property="og:image" content="<?php echo $imgUrl; ?>" />
        <meta property="og:url" content="<?php echo $product->getProductUrl();?>" />
        <meta property="og:description" content="<?php echo  $product->getDescription(); ?>" />
    <?php else: ?>
        <meta property="og:title" content="<?php echo  Mage::getStoreConfig('design/head/default_title', Mage::app()->getStore()->getId()); ?>"/>  
        <meta property="og:image" content="<?php echo $this->getSkinUrl("images/logo_alpha.png");?>" />
        <meta property="og:url" content="<?php echo $this->getUrl(); ?>" />
        <meta property="og:description" content="<?php echo  Mage::getStoreConfig('design/head/default_title', Mage::app()->getStore()->getId()); ?>" />
    <?php endif; ?>    
<?php endif; ?>    
