<?php
/**
 * visaulizzo il pulsante like per la pagina corrente.
 * Se sono loggato non metto il tag fb-root perchè è già creato per il facebook connect
 * altrimenti lo forzo 
 * <div id="fb-root">
 *   
 * </div>
 * <script src="http://connect.facebook.net/en_US/all.js#appId=267246793303355&amp;xfbml=1"></script> 
 */
?>
<div>
<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <div id="fb-root"></div>
    <script src="http://connect.facebook.net/en_US/all.js#appId=<?php echo $this->getFBSetting("appId");?> &amp;xfbml=1"></script> 
<?php endif; ?>
<fb:like href="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>" 
         send="true" width="320" show_faces="false" font=""></fb:like>
</div>
    