<?php 
/**
 * IDEALIAGroup srl
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.idealiagroup.com/magento-ext-license.html
 *
 * @category   IG
 * @package    IG_EuroSuite
 * @copyright  Copyright (c) 2010-2011 IDEALIAGroup srl (http://www.idealiagroup.com)
 * @license    http://www.idealiagroup.com/magento-ext-license.html
 */
?>

<?php
$eurosuite = Mage::getModel('ig_eurosuite/eurosuite');
?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contacts_copy')->toHtml() ?>
<div style="clear: both;"></div>
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                <div class="input-box">
                    <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                </div>
            </li>
            <li class="wide">
                <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                <div class="input-box">
                    <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
	
	<?php if (
		$eurosuite->isEnabled() &&
		($eurosuite->isPrivacyRequired('contacts') || $eurosuite->isTosRequired('contacts'))
	): ?>
	<div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Terms of service') ?></h2>
        <ul class="form-list">
        	<?php if ($eurosuite->isPrivacyRequired('contacts')): ?>
            <li class="control">
				<div class="input-box">
					<input type="checkbox" name="privacy" id="privacy" class="checkbox required-entry" />
				</div>
				<label for="privacy" class="required"><em>*</em><?php echo Mage::helper('ig_eurosuite/tos')->getPrivacyText() ?></label>
			</li>
			<?php endif; ?>
			<?php if ($eurosuite->isTosRequired('contacts')): ?>
			<li class="control">
				<div class="input-box">
					<input type="checkbox" name="tos" id="tos" class="checkbox required-entry" />
				</div>
				<label for="tos" class="required"><em>*</em><?php echo Mage::helper('ig_eurosuite/tos')->getTosText() ?></label>
            </li>
			<?php endif; ?>
        </ul>
    </div>
	<?php endif; ?>

    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
