<div class="set-container">
    <div class="set-left">
        <div class="set-1">
            <?php echo ($this->isBlock(1)) ? $this->getBlockHtml(1) : ""; ?>
        </div>
        <div class="set-2">
            <?php echo ($this->isBlock(2)) ? $this->getBlockHtml(2) : ""; ?>
        </div>
    </div>
    <div class="set-3 set-right">
        <?php echo ($this->isBlock(3)) ? $this->getBlockHtml(3) : ""; ?>
    </div>
</div>