<style>
    .set-container {width: 100%; height: auto; border: 1px solid}
    .set-container .set-left {float: left}
    .set-container .set-right {float: right} 
    .set-container>div {border: 1px solid;}
    .set-container>div {border: 1px solid red}
</style>

<div class="set-container">
    <div class="set-left">
        <div class="set-1">
            
        </div>
        <div class="set-2">
            
        </div>
    </div>
    <div class="set-3">
        
    </div>
</div>