<div id="homeSet">
<ul>
	<li>
		is <span class="titoloGrassetto"><?php echo $this->__('sorrento set'); ?></span>
		<a class="sfondoSet" href="#" title="Sorrento set">
		<img src="media/template/fotoHome01.jpg" border="0">
		</a>
		 <span class="sottotitoloSet"><?php echo $this->__('READ&SHOP'); ?></span>
	</li>
	<li>
		is <span class="titoloGrassetto"><?php echo $this->__('old italian cases set'); ?></span>
		<a class="sfondoSet" href="#" title="Sorrento set">
		<img src="media/template/fotoHome02.jpg" border="0">
		</a>
		<span class="sottotitoloSet"><?php echo $this->__('READ&SHOP'); ?></span>
	</li>
	<li>
		is <span class="titoloGrassetto"><?php echo $this->__('rome 70\'s set'); ?></span>
		<a class="sfondoSet" href="#" title="Sorrento set">
		<img src="media/template/fotoHome03.jpg" border="0">
		</a>
		<span class="sottotitoloSet"><?php echo $this->__('READ&SHOP'); ?></span>
	</li>
	<li>
		is <span class="titoloGrassetto"><?php echo $this->__('tuscany wines set'); ?></span>
		<a class="sfondoSet" href="#" title="Sorrento set">
		<img src="media/template/fotoHome04.jpg" border="0">
		</a>
		<span class="sottotitoloSet"><?php echo $this->__('READ&SHOP'); ?></span>
	</li>
</ul>
</div>
<div class="spaziatoreLungo" >
	<hr/>
</div>
