<?php

?>
<?php 
/**
 * Store switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */
?>
<div class="country-switcher header-selector-pop-up" style="display: none;">
    <div class="country-move up"></div>
    <div class ="country-all" style="position: relative; overflow: hidden">
        <div class="country-list">
        <?php
            $i = 0;
            foreach (Mage::Helper('veredus/local')->getAllowCountry() as $_country):
        ?>    
        <div class="block-country header-selector" rel="<?php echo $i++;?>">
            <a href="<?php echo $this->getUrl('veredus/local/setcountry/', array('code' => $_country->getCountryId()));?>">
                <?php echo $_country->getName();?>
            </a>
        </div>
        <?php
            endforeach;
        ?>
        </div>
    </div>
    <div class="country-move down"></div>
</div>

<script>
    Translator.add('waitingImage', "<?php echo $this->getSkinUrl('images/waiting.gif');?>");
</script>
