<?php $_maincategorylisting=$this->getCurrentCategory()?>
<?php $_categories=$this->getCurrentChildCategories()?>
<div class="category-listing-head">
 <?php echo 'ciso' . $this->getLayout()->createBlock('cms/block')->setBlockId('brand_listing_head')->toHtml() ?> 
</div>
<?php 
  $pagerBlock = $this->getLayout()->createBlock('page/html_pager')->setTemplate('page/html/pager.phtml');
  $pagerBlock->setAvailableLimit(array(12=>12,24=>24,36=>36));
  $pagerBlock->setCollection($_categories);
  $pagerBlock->setShowPerPage(true);
  $pages = $pagerBlock->getPages();
  $_categories->setPageSize( $pagerBlock->getLimit());
  $_categories->setCurPage($pagerBlock->getCurrentPage());
  $pagerBlock->setLastPageNum(count($pages));
  $pageCategories = array();
  $i=0;
  $firstPageIndex = ($pagerBlock->getCurrentPage()-1)*$pagerBlock->getLimit();
  $lastPageIndex = $firstPageIndex+$pagerBlock->getLimit();
  if($pagerBlock->getCurrentPage()>count($pages)){
    $firstPageIndex = 0;
    $lastPageIndex = $pagerBlock->getLimit();
  }
  foreach($_categories as $category){
    if($i>=$firstPageIndex && $i<$lastPageIndex){
      array_push($pageCategories, $category);
    }
    $i++;
  }
  
  echo $pagerBlock->toHtml();
?>
<!--<h2><?php echo $this->__('Browse Products') ?> </h2>-->
<div class="subcat-listing">
<?php
  $index = 0; 
  foreach ($pageCategories as $_category){ 
    if($_category->getIsActive()){
      $cur_category=Mage::getModel('catalog/category')->load($_category->getId());
      $layer = Mage::getSingleton('catalog/layer');
      $layer->setCurrentCategory($cur_category);
      $_imageUrl=Mage::getBaseUrl('media').'catalog/category/'.$this->getCurrentCategory()->getThumbnail();
      if($index%3==0){
        echo "<ul class=\"subcat-products\">";
      }
 ?>
      <li>
        <?php echo $this->__('is'); ?>
        <span class="titoloGrassetto"><?php echo $this->htmlEscape($_category->getName()) ?></span>
        <a class="sfondoSet" href="<?php echo $this->getCategoryUrl($_category) ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>">
          <img src="<?php echo $_imageUrl ?>"  alt="<?php echo $this->htmlEscape($_category->getName()) ?>" />
        </a>
        <span class="sottotitoloSet">
          <a href="<?php echo $this->getCategoryUrl($_category) ?>"><?php echo $this->__('READ&SHOP'); ?></a>
        </span>
        <?php if($_description=$this->getCurrentCategory()->getDescription()){?>
          <p class="category-description">
          </p>
        <?php } //if?>
      </li>
     <?php 
          if($index%3==2 || $index == count($_categories)-1){
            echo "</ul>";
            echo "<hr class=\"spaziatoreLungo spaziatoreLungoBrands\">";
          }
          $index = $index+1;
           } //if?>
<?php } //foreach?>
</div>
<?php 
  $pagerBlock->setShowPerPage(false);
  echo $pagerBlock->toHtml(); 
?>
<?php $layer->setCurrentCategory($_maincategorylisting); ?>
